Docker : Fix Dockerfile inspired by Kubo official Dockerfile
ipfs/go-ds-s3 pull request #291
Opened 2024-05-01 19:16 UTC by FournyP

Hi,

I've done this little change in the Dockerfile on my side for a personal project.

The build is clearly inspired by the official [Kubo Dockerfile](https://github.com/ipfs/kubo/blob/master/Dockerfile).
Imo it's make more sense than the older one.

It also bring the flexibility of the Kubo Dockerfile.

And the jq depency is downloaded in another FROM for paralleling purpose (as Kubo Dockerfile do in the `utilities` FROM).

![image](https://github.com/ipfs/go-ds-s3/assets/64586968/92681d08-ffac-4be6-9e70-4c6cb8b89df5)
![image](https://github.com/ipfs/go-ds-s3/assets/64586968/8131fe31-9688-4eb4-8714-fab946aad104)

Errors on the screen are because I didn't map the ports

Have a nice day

2024-08-27 17:01 UTC, lidel commented
Triage notes:
- We will revisit this after Kubo 0.30 ships (https://github.com/ipfs/kubo/issues/10436)

2024-09-03 16:50 UTC, lidel commented on docker/Dockerfile
> +RUN git clone --branch v0.28.0 https://github.com/ipfs/kubo.git .
- [ ] TODO: switch to Kubo 0.30 once it ships

2024-09-03 16:51 UTC, lidel commented on docker/Dockerfile
> +FROM ipfs/kubo:v0.28.0
- [ ] Kubo 0.30 once it ships

2024-09-17 16:49 UTC, lidel requested changes
@FournyP do you mind switching to Kubo 0.30 and confirming things work as expected?

2024-12-11 01:44 UTC, gammazero commented on docker/Dockerfile
> +FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:1.22 AS builder
```suggestion
FROM --platform=${BUILDPLATFORM:-linux/amd64} golang:1.23 AS builder
```

2026-05-19 19:09 UTC, closed without merging